id = 1
title = "Beta task one"
description = "Another example task."
status = "started"
acceptance = []
context = ""
priority = "high"
labels = []
links = []
report_problems = []
report_ideas = []
report_decisions = []
created_at = "2026-08-25T00:00:00"
started_at = "2026-08-25T00:00:00"
updated_at = "2026-08-25T00:00:00"
